<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\KayraExport.Microservices.BuildingBlocks.Shared.Core\KayraExport.Microservices.BuildingBlocks.Shared.Application.csproj" />
    <ProjectReference Include="..\KayraExport.Microservices.Services.Product.Domain\KayraExport.Microservices.Services.Product.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="CQRS\Product\Commands\Insert\" />
    <Folder Include="CQRS\Product\Commands\Delete\" />
    <Folder Include="CQRS\Product\Commands\Update\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.5" />
  </ItemGroup>

</Project>
