<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\KayraExport.Microservices.Services.Log.Core\KayraExport.Microservices.Services.Log.Core.csproj" />
  </ItemGroup>

</Project>
