// <auto-generated />
using System;
using KayraExport.Microservices.Services.Product.Infrastructure.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KayraExport.Microservices.Services.Product.Infrastructure.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20260329073543_mig_3")]
    partial class mig_3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KayraExport.Microservices.Services.Product.Domain.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("products", "product", t =>
                        {
                            t.HasCheckConstraint("CK_Products_Price_NotNegative", "\"Price\" >= 0");

                            t.HasCheckConstraint("CK_Products_StockQuantity_NotNegative", "\"StockQuantity\" >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Samsung Tab S10 FE",
                            Name = "Samsung Tablet",
                            Price = 22000m,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "IPhone 17 Pro",
                            Name = "Apple Telefon",
                            Price = 74899m,
                            StockQuantity = 5
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Logitech Mx Key Mini",
                            Name = "Logitech Klavye",
                            Price = 4022.74m,
                            StockQuantity = 18
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Con Sinov'dan Yarının Adamı 1 - Mustafa Kemal'i Anlamak",
                            Name = "Atatürk Kitabı",
                            Price = 249.40m,
                            StockQuantity = 78
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sony WH-CH520",
                            Name = "Sony Kulaklık",
                            Price = 2599m,
                            StockQuantity = 4
                        },
                        new
                        {
                            Id = 6L,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gri Abajur",
                            Name = "Abajur",
                            Price = 341.35m,
                            StockQuantity = 89
                        },
                        new
                        {
                            Id = 7L,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Dell S2721DS 27 inch Monitör",
                            Name = "Dell Monitör",
                            Price = 9865.21m,
                            StockQuantity = 9
                        },
                        new
                        {
                            Id = 8L,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mustang Güneş Gözlüğü",
                            Name = "Güneş Gözlüğü",
                            Price = 2983.89m,
                            StockQuantity = 16
                        },
                        new
                        {
                            Id = 9L,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ahşap Yemek Masası",
                            Name = "Yemek Masası",
                            Price = 1799.87m,
                            StockQuantity = 5
                        },
                        new
                        {
                            Id = 10L,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Dell 32 GB Ram Laptop",
                            Name = "Dell Laptop",
                            Price = 43899.89m,
                            StockQuantity = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
